# frozen_string_literal: true

source 'https://rubygems.org'

# git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'pry'
gem 'pry-byebug'
gem 'pry-doc'
gem 'puma'
gem 'rack-contrib'
gem 'sinatra'
gem 'zeitwerk'

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'rubocop'
end
